import {
  CONVERSATION_PERMISSIONS,
  CONTACT_PERMISSIONS,
  CONTACT_INBOX_PERMISSIONS,
  REPORT_PAGE_PERMISSIONS,
} from 'dashboard/constants/permissions.js';

export const CONVERSATION_PERMISSION_OPTIONS = CONVERSATION_PERMISSIONS;

export const CONTACT_SCOPE_OPTIONS = [
  CONTACT_INBOX_PERMISSIONS,
  CONTACT_PERMISSIONS,
];

export const CONTACT_ACTION_PERMISSIONS = ['contact_edit', 'contact_delete'];

export const REPORT_PERMISSION_OPTIONS = REPORT_PAGE_PERMISSIONS;
