// Auto-generated by `pnpm sdk:wsc`. Placeholder to avoid import errors in dev.
// CI regenerates this file from swagger/wsc/openapi.yaml on install and on PR checks.
export interface paths {}
export interface components {}
export type operations = never;

