"""Centralised configuration, loaded from environment (12-factor)."""
from __future__ import annotations

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Bootstrap + infra config from the environment.

    User-facing API keys (Anthropic, KeyCRM, Chatwoot token, Langfuse, channel tokens) are NOT
    set here in production — they're entered in the admin panel and overlaid at runtime by
    ``settings_service``. The values below act as defaults/fallbacks so the service still boots
    and tests run without a database.
    """

    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Bootstrap secret (generated by deploy.sh). Encrypts panel secrets + signs admin sessions.
    # This is the ONLY secret the operator never types into the UI.
    app_secret_key: str = "dev-insecure-change-me"

    # Settings store / admin DB. Own `omni_ai` database on the shared Postgres. Named with an
    # `omni_` prefix so it can't collide with Chatwoot's own DATABASE_URL in the shared .env.
    omni_database_url: str = "postgresql+asyncpg://chatwoot:chatwoot@postgres:5432/omni_ai"

    # Public URL of this service (used to render webhook/embed snippets in the panel).
    public_base_url: str = "http://localhost:8080"

    # Internal URL Chatwoot uses to reach this service for agent-bot/API-channel webhooks
    # (server-to-server inside the compose network — independent of the public proxy/TLS).
    internal_base_url: str = "http://ai-service:8080"

    # Chatwoot (Unified Chat Panel)
    chatwoot_base_url: str = "http://chatwoot:3000"
    chatwoot_api_access_token: str = ""
    chatwoot_account_id: int = 1
    chatwoot_hmac_secret: str = ""

    # Model gateway (provider-agnostic; Claude primary)
    litellm_base_url: str = "http://litellm:4000"
    litellm_master_key: str = "sk-omni-local"
    agent_model: str = "claude-primary"

    # KeyCRM
    keycrm_base_url: str = "https://openapi.keycrm.app/v1"
    keycrm_api_key: str = ""

    # Observability / eval
    langfuse_host: str = "http://langfuse:3000"
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""

    # Connectors (non-native channels via E-Chat.tech bridge)
    echat_base_url: str = "https://api.e-chat.tech"
    echat_api_key: str = ""
    echat_webhook_secret: str = ""

    # RAG
    qdrant_url: str = "http://qdrant:6333"
    # Local fastembed model for KB embeddings. Empty = fastembed default (English). Set a
    # multilingual model (e.g. intfloat/multilingual-e5-large) for non-English catalogues.
    kb_embedding_model: str = ""


settings = Settings()
