"""Symmetric encryption for secrets at rest.

API keys entered in the admin panel are stored encrypted in Postgres. We derive a stable
Fernet key from the single bootstrap secret ``APP_SECRET_KEY`` (generated by deploy.sh), so the
operator never manages encryption keys directly. Rotating ``APP_SECRET_KEY`` invalidates stored
secrets by design — they're simply re-entered in the panel.
"""
from __future__ import annotations

import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken

from .config import settings


def _fernet() -> Fernet:
    # Fernet needs a 32-byte urlsafe-base64 key; derive one deterministically from the secret.
    digest = hashlib.sha256(settings.app_secret_key.encode()).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def seal(plaintext: str) -> bytes:
    """Encrypt a secret value for storage."""
    return _fernet().encrypt(plaintext.encode())


def open_secret(token: bytes) -> str:
    """Decrypt a stored secret. Returns "" if the token can't be read (e.g. rotated key)."""
    try:
        return _fernet().decrypt(bytes(token)).decode()
    except (InvalidToken, ValueError):
        return ""
