#!/usr/bin/env node

/**
* @license Apache-2.0
*
* Copyright (c) 2018 The Stdlib Authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

'use strict';

// MODULES //

var resolve = require( 'path' ).resolve;
var cwd = require( 'process' ).cwd; // Note: avoiding `@stdlib/process/cwd` is intentional in order to avoid a circular dependency at the package level
var CLI = require( '@stdlib/cli-ctor' );
var readFile = require( './../lib' );


// MAIN //

/**
* Main execution sequence.
*
* @private
* @returns {void}
*/
function main() {
	var fpath;
	var flags;
	var args;
	var opts;
	var cli;

	// Create a command-line interface:
	cli = new CLI({
		'pkg': require( './../package.json' ),
		'options': require( './../etc/cli_opts.json' ),
		'help': readFile.sync( resolve( __dirname, '..', 'docs', 'usage.txt' ), {
			'encoding': 'utf8'
		})
	});

	// Get any provided command-line options:
	flags = cli.flags();
	if ( flags.help || flags.version ) {
		return;
	}

	// Get any provided command-line arguments:
	args = cli.args();

	opts = {};
	if ( flags.encoding ) {
		opts.encoding = flags.encoding;
	}
	if ( flags.flag ) {
		opts.flag = flags.flag;
	}

	fpath = resolve( cwd(), args[ 0 ] );
	readFile( fpath, opts, onFile );

	/**
	* Callback invoked upon reading the contents of a file.
	*
	* @private
	* @param {(Error|null)} error - error object
	* @param {(Buffer|string)} file - file contents
	* @returns {void}
	*/
	function onFile( error, file ) {
		if ( error ) {
			return cli.error( error );
		}
		console.log( file.toString() ); // eslint-disable-line no-console
	}
}

main();
