# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Converso'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/converso/logo.png'
- name: LOGO
  value: '/brand-assets/converso/logo.png'
- name: LOGO_DARK
  value: '/brand-assets/converso/logo_dark.png'
- name: BRAND_URL
  value: 'https://converso.cybroscloud.com'
- name: WIDGET_BRAND_URL
  value: 'https://converso.cybroscloud.com'
- name: BRAND_NAME
  value: 'Converso'
- name: TERMS_URL
  value: 'https://converso.cybroscloud.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://converso.cybroscloud.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
