import { Properties } from '../types';
export declare const PERSONAL_DATA_CAMPAIGN_PARAMS: string[];
export declare const CAMPAIGN_PARAMS: string[];
export declare const EVENT_TO_PERSON_PROPERTIES: string[];
export declare const MASKED = "<masked>";
export declare const COOKIE_CAMPAIGN_PARAMS: string[];
export declare function getCampaignParams(customTrackedParams?: string[], maskPersonalDataProperties?: boolean, customPersonalDataProperties?: string[] | undefined): Record<string, string>;
export declare function getSearchInfo(): Record<string, any>;
export declare function getBrowserLanguage(): string | undefined;
export declare function getBrowserLanguagePrefix(): string | undefined;
export declare function getReferrer(): string;
export declare function getReferringDomain(): string;
export declare function getReferrerInfo(): Record<string, any>;
export declare function getPersonInfo(maskPersonalDataProperties?: boolean, customPersonalDataProperties?: string[]): {
    r: string;
    u: string | undefined;
};
export declare function getPersonPropsFromInfo(info: Record<string, any>): Record<string, any>;
export declare function getInitialPersonPropsFromInfo(info: Record<string, any>): Record<string, any>;
export declare function getTimezone(): string | undefined;
export declare function getTimezoneOffset(): number | undefined;
export declare function getEventProperties(maskPersonalDataProperties?: boolean, customPersonalDataProperties?: string[]): Properties;
