json.email contact.email
json.id contact.id
json.name contact.name
json.phone_number contact.phone_number
json.additional_emails contact.additional_emails
json.email_addresses contact.all_emails
json.additional_phones contact.additional_phones
json.phone_numbers contact.all_phone_numbers
json.identifier contact.identifier
json.additional_attributes contact.additional_attributes
json.last_activity_at contact.last_activity_at&.to_i
