version: "2"
plugins:
  rubocop:
    enabled: false
    channel: rubocop-0-73
  eslint:
    enabled: false
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  brakeman:
    enabled: false
checks:
  similar-code:
    enabled: false
exclude_patterns:
  - "spec/"
  - "**/specs/"
  - "db/*"
  - "bin/**/*"
  - "db/**/*"
  - "config/**/*"
  - "public/**/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "lib/tasks/auto_annotate_models.rake"
  - "app/test-matchers.js"
  - "docs/*"
  - "**/*.md"
  - "**/*.yml"
  - "app/javascript/dashboard/i18n/locale"
  - "**/*.stories.js"
  - "stories/**/*"
  - "**/*.stories.js"
  - "**/stories/"
