require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 150
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
RSpec/NestedGroups:
  Enabled: true
  Max: 4
AllCops:
  Exclude:
    - db/*
    - bin/**/*
    - db/**/*
    - config/**/*
    - public/**/*
    - vendor/**/*
    - node_modules/**/*
