# Cloud Run Service Configuration for Chatwoot Worker (Sidekiq)
# Use: gcloud run services replace cloudrun-worker.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatwoot-worker
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/vpc-access-connector: chatwoot-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:chatwoot-postgres
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 600
      serviceAccountName: chatwoot-service-account@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: chatwoot-worker
        image: gcr.io/PROJECT_ID/chatwoot:amb-beta

        command:
        - bundle
        args:
        - exec
        - sidekiq
        - -C
        - config/sidekiq.yml

        resources:
          limits:
            cpu: "1000m"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi

        env:
        # Rails Configuration
        - name: RAILS_ENV
          value: production
        - name: LOG_LEVEL
          value: info

        # Database Configuration
        - name: POSTGRES_HOST
          value: /cloudsql/PROJECT_ID:REGION:chatwoot-postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: chatwoot_production
        - name: POSTGRES_USERNAME
          value: chatwoot_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chatwoot-db-password
              key: latest

        # Redis Configuration
        - name: REDIS_URL
          value: redis://REDIS_HOST:6379

        # Application Configuration
        - name: FRONTEND_URL
          value: https://your-domain.com

        # Secret Key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: chatwoot-secret-key-base
              key: latest

        # Active Record Encryption (for 2FA)
        - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
          valueFrom:
            secretKeyRef:
              name: chatwoot-encryption-primary-key
              key: latest
        - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
          valueFrom:
            secretKeyRef:
              name: chatwoot-encryption-deterministic-key
              key: latest
        - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
          valueFrom:
            secretKeyRef:
              name: chatwoot-encryption-derivation-salt
              key: latest

        # Storage Configuration
        - name: ACTIVE_STORAGE_SERVICE
          value: google
        - name: GCS_PROJECT
          value: PROJECT_ID
        - name: GCS_BUCKET
          value: PROJECT_ID-chatwoot-storage

        # Apple Messages for Business
        - name: APPLE_MSP_BASE_URL
          value: https://api.business.apple.com/v1
        - name: APPLE_MSP_TOKEN
          valueFrom:
            secretKeyRef:
              name: apple-msp-token
              key: latest
        - name: APPLE_MSP_KEY_ID
          valueFrom:
            secretKeyRef:
              name: apple-msp-key-id
              key: latest

        # Sidekiq Configuration
        - name: SIDEKIQ_CONCURRENCY
          value: "10"