version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gp-bikes-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatwoot_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-chatwoot_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-extensions.sql:/docker-entrypoint-initdb.d/01-init-extensions.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gp-bikes-network
    platform: linux/amd64

  redis:
    image: redis:7-alpine
    container_name: gp-bikes-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - gp-bikes-network
    platform: linux/amd64

volumes:
  postgres_data:
    name: gp-bikes-postgres-data
  redis_data:
    name: gp-bikes-redis-data

networks:
  gp-bikes-network:
    name: gp-bikes-network
    driver: bridge
