version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:v4.9.1
    env_file: .env
    volumes:
      - ./:/app:delegated
      - node_modules_new:/app/node_modules
      - packs_new:/app/public/packs
      - cache_new:/app/tmp/cache
      - bundle_new:/usr/local/bundle

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - VITE_DEV_SERVER_HOST=vite
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  vite:
    <<: *base
    ports:
      - "3037:3036" # Vite dev server on host 3037
    environment:
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - RAILS_ENV=development
    entrypoint: docker/entrypoints/vite.sh
    command: tail -f /dev/null

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgres-new:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis-new:/data/redis
    ports:
      - '6380:6379'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1026:1025
      - 8026:8025

volumes:
  postgres-new:
  redis-new:
  packs_new:
  node_modules_new:
  cache_new:
  bundle_new:
