version: '3'

services:
  base: &base
    image: ghcr.io/on-cruise-control/courier:staging
    env_file: .env ## Change this file for customized env variables
    volumes:
      - storage_data:/app/storage

  rails:
    <<: *base
    depends_on:
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - VITE_RUBY_RUN_NODE_COMMAND=false
      - VITE_RUBY_AUTO_BUILD=false
      - RAILS_SERVE_STATIC_FILES=true
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - VITE_RUBY_RUN_NODE_COMMAND=false
      - VITE_RUBY_AUTO_BUILD=false
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  storage_data:
  redis_data:
