module.exports = {
  apps: [
    {
      name: 'chatwoot-web',
      script: './bin/pm2-web.sh',
      cwd: '/home/deltatec/develop/chatwoot',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        RAILS_ENV: 'development',
        PORT: 3000,
      },
      env_file: '.env',
      error_file: './log/pm2-web-error.log',
      out_file: './log/pm2-web-out.log',
      log_file: './log/pm2-web-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'chatwoot-worker',
      script: './bin/pm2-worker.sh',
      cwd: '/home/deltatec/develop/chatwoot',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        RAILS_ENV: 'development',
      },
      env_file: '.env',
      error_file: './log/pm2-worker-error.log',
      out_file: './log/pm2-worker-out.log',
      log_file: './log/pm2-worker-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
    },
  ],
};

