version: '3'

env:
  COMPOSE_FILE: docker-compose.yaml

tasks:
  # ---------------------------------------------------------------------
  # docker
  # ---------------------------------------------------------------------
  docker-build-base:
    desc: "Build base Docker image"
    cmds:
      - docker compose build base
    
  docker-build:
    desc: "Build all Docker images"
    deps:
      - docker-build-base
    cmds:
      - docker compose build

  docker-setup-dev:
    desc: "Setup Docker development images"
    cmds:
      - docker compose run --rm rails bundle exec rails db:chatwoot_prepare

  docker-setup-test:
    desc: "Setup Docker unit-test images"
    cmds:
      - docker compose run --rm rails bundle exec rails db:chatwoot_prepare RAILS_ENV=test
    
  docker-test:
    desc: "Run the full RSpec suite inside the Rails container"
    cmds:
      - docker compose run --rm -e RAILS_ENV=test rails bundle exec rspec --profile=10 --format documentation
    silent: true

  docker-up:
    desc: "Start the Docker containers"
    cmds:
      - docker compose up -d

  docker-clean-volumes:
    desc: "Delete all Docker volumes"
    cmds:
      - echo "Stopping and removing containers..."
      - docker compose down -v --remove-orphans
      - docker volume prune -f
      - echo "Volume cleanup completed!"

