version: '3'

env:
  COMPOSE_FILE: docker-compose.yaml

tasks:
  # ---------------------------------------------------------------------
  # docker
  # ---------------------------------------------------------------------
  docker-build-base:
    desc: "Build base Docker image"
    cmds:
      - docker compose build base

  docker-setup-dev:
    desc: "Setup Docker development images"
    cmds:
      - docker compose build
      - docker compose run --rm rails bundle exec rails db:chatwoot_prepare

  docker-setup-test:
    desc: "Setup Docker unit-test images"
    cmds:
      - docker compose build
      - docker compose run --rm rails bundle exec rails db:chatwoot_prepare RAILS_ENV=test
    
  docker-test:
    desc: "Run the full RSpec suite inside the Rails container"
    cmds:
      - docker compose run --rm -e RAILS_ENV=test rails bundle exec rspec --profile=10 --format documentation
    silent: true

  docker-clean-volumes:
    desc: "Delete all Docker volumes"
    cmds:
      - echo "Stopping and removing containers..."
      - docker compose down -v --remove-orphans
      - docker volume prune -f
      - echo "Volume cleanup completed!"

  test:
    desc: "Run the full RSpec suite locally"
    cmds:
      - export PGHOST=host.docker.internal
      - export PGPORT=5432 PGUSER=postgres PGPASSWORD=postgres
      - unset SMTP_ADDRESS SMTP_USERNAME SMTP_PASSWORD
      - bundle exec rails db:chatwoot_prepare RAILS_ENV=test
      - bundle exec rspec --profile=10 --format documentation
    silent: true
