export default {
  allAgents: [
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'John K',
      confirmed: true,
      email: 'john@chatwoot.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@chatwoot.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
  ],
  formattedAgents: [
    {
      account_id: 0,
      confirmed: true,
      email: 'None',
      id: 0,
      name: 'None',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'John K',
      confirmed: true,
      email: 'john@chatwoot.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@chatwoot.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
  ],
};
