export type JSONSyntaxContext = {
    trailingCommas: boolean;
    comments: boolean;
    plusSigns: boolean;
    spacedSigns: boolean;
    leadingOrTrailingDecimalPoints: boolean;
    infinities: boolean;
    nans: boolean;
    numericSeparators: boolean;
    binaryNumericLiterals: boolean;
    octalNumericLiterals: boolean;
    legacyOctalNumericLiterals: boolean;
    invalidJsonNumbers: boolean;
    multilineStrings: boolean;
    unquoteProperties: boolean;
    singleQuotes: boolean;
    numberProperties: boolean;
    undefinedKeywords: boolean;
    sparseArrays: boolean;
    regExpLiterals: boolean;
    templateLiterals: boolean;
    bigintLiterals: boolean;
    unicodeCodepointEscapes: boolean;
    escapeSequenceInIdentifier: boolean;
    parentheses: boolean;
    staticExpressions: boolean;
};
