export default [
  {
    id: 1,
    title: 'Как подключить SSL для собственного домена help-center.kz',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: 'Айдана' },
    category: {
      slug: 'nastroyka-portala',
      icon: '📦',
      name: 'Настройка портала',
    },
    views: 3400,
  },
  {
    id: 2,
    title: 'Запуск первого портала поддержки для клиентов в Казахстане',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Руслан' },
    category: { slug: 'start', icon: '🧑‍🍳', name: 'Быстрый старт' },
    views: 400,
  },
  {
    id: 3,
    title: 'Как структурировать статьи по доставке, оплате и возвратам',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: 'Меруерт' },
    category: { slug: 'praktika', icon: '⛺️', name: 'Лучшие практики' },
    views: 400,
  },
  {
    id: 4,
    title: 'Как настроить фирменный стиль портала OneLink',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: 'Алия' },
    category: { slug: 'design', icon: '🎨', name: 'Дизайн' },
    views: 400,
  },
  {
    id: 5,
    title: 'Интеграции с Kaspi, WhatsApp и CRM: базовый сценарий',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Тимур' },
    category: {
      slug: 'integrations',
      icon: '🔗',
      name: 'Интеграции',
    },
    views: 2800,
  },
  {
    id: 6,
    title: 'Роли редакторов, агентов и администраторов в базе знаний',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: 'Дамир' },
    category: {
      slug: 'administration',
      icon: '🔐',
      name: 'Администрирование',
    },
    views: 1200,
  },
  {
    id: 7,
    title: 'Как оформить FAQ по доставке по регионам Казахстана',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Сая' },
    category: {
      slug: 'faq',
      icon: '📝',
      name: 'Управление контентом',
    },
    views: 5600,
  },
  {
    id: 8,
    title: 'Настройка поиска по статьям и подсказкам для операторов',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: 'Нурлан' },
    category: {
      slug: 'features',
      icon: '🔍',
      name: 'Функции',
    },
    views: 1800,
  },
  {
    id: 9,
    title: 'Какие метрики смотреть по базе знаний каждую неделю',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Айгерим' },
    category: {
      slug: 'analytics',
      icon: '📊',
      name: 'Аналитика',
    },
    views: 3200,
  },
  {
    id: 10,
    title: 'Как включить русский и казахский языки в центре поддержки',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: 'Жанна' },
    category: {
      slug: 'localization',
      icon: '🌍',
      name: 'Локализация',
    },
    views: 900,
  },
  {
    id: 11,
    title: 'Интерактивные инструкции для новых операторов и клиентов',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Арсен' },
    category: {
      slug: 'education',
      icon: '🎓',
      name: 'Обучение',
    },
    views: 4100,
  },
  {
    id: 12,
    title: 'Как собирать обратную связь после прочтения статьи',
    status: 'draft',
    updatedAt: 1729205669,
    author: { availableName: 'Дина' },
    category: {
      slug: 'feedback',
      icon: '💬',
      name: 'Обратная связь',
    },
    views: 750,
  },
  {
    id: 13,
    title: 'SEO для статей: как занимать выдачу по брендовым запросам',
    status: 'published',
    updatedAt: 1729205669,
    author: { availableName: 'Ержан' },
    category: {
      slug: 'seo',
      icon: '🚀',
      name: 'SEO',
    },
    views: 2900,
  },
  {
    id: 14,
    title: 'Внутренняя база знаний для операторов и отдела контроля качества',
    status: 'archived',
    updatedAt: 1729205669,
    author: { availableName: 'Айнур' },
    category: {
      slug: 'internal-resources',
      icon: '🏢',
      name: 'Внутренние ресурсы',
    },
    views: 1500,
  },
];
