export const SET_WIDGET_COLOR = 'SET_WIDGET_COLOR';
export const SET_CONVERSATION_ATTRIBUTES = 'SET_CONVERSATION_ATTRIBUTES';
export const UPDATE_CONVERSATION_ATTRIBUTES = 'UPDATE_CONVERSATION_ATTRIBUTES';

export const SET_CONVERSATIONS_UI_FLAGS = 'SET_CONVERSATIONS_UI_FLAGS';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
