name: wasl-chat

region: fra

services:
  - name: web
    github:
      repo: proahmedalraey/wasl
      branch: develop
      deploy_on_push: true

    source_dir: /

    environment_slug: ruby
    instance_count: 1
    instance_size_slug: basic-s

    http_port: 3000

    routes:
      - path: /

    build_command: |
      bundle install
      bundle exec rails assets:precompile
      bundle exec rails db:prepare

    run_command: |
      bundle exec rails server -p 3000 -e production -b 0.0.0.0

    envs:
      - key: RAILS_ENV
        value: production

      - key: NODE_ENV
        value: production

      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

      - key: RAILS_LOG_TO_STDOUT
        value: "true"

      - key: INSTALLATION_ENV
        value: digitalocean_app_platform

      - key: FRONTEND_URL
        value: https://folathparfum.com

      - key: SECRET_KEY_BASE
        type: SECRET

      - key: POSTGRES_HOST
        value: ${db.HOSTNAME}

      - key: POSTGRES_PORT
        value: ${db.PORT}

      - key: POSTGRES_DATABASE
        value: ${db.DATABASE}

      - key: POSTGRES_USERNAME
        value: ${db.USERNAME}

      - key: POSTGRES_PASSWORD
        value: ${db.PASSWORD}
        type: SECRET

      - key: REDIS_URL
        value: ${redis.REDIS_URL}

      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
        type: SECRET

      - key: ENABLE_ACCOUNT_SIGNUP
        value: "false"

      - key: DEFAULT_LOCALE
        value: en

      - key: ACTIVE_STORAGE_SERVICE
        value: local

      - key: MAILER_SENDER_EMAIL
        value: support@folathparfum.com

      - key: SMTP_ADDRESS
        value: smtp.hostinger.com

      - key: SMTP_PORT
        value: "587"

      - key: SMTP_USERNAME
        value: support@folathparfum.com

      - key: SMTP_PASSWORD
        type: SECRET

      - key: SMTP_DOMAIN
        value: folathparfum.com

      - key: SMTP_AUTHENTICATION
        value: login

      - key: SMTP_ENABLE_STARTTLS_AUTO
        value: "true"

  - name: worker
    github:
      repo: proahmedalraey/wasl
      branch: develop
      deploy_on_push: true

    source_dir: /

    environment_slug: ruby
    instance_count: 1
    instance_size_slug: basic-s

    build_command: |
      bundle install

    run_command: |
      bundle exec sidekiq -C config/sidekiq.yml

    envs:
      - key: RAILS_ENV
        value: production

      - key: NODE_ENV
        value: production

      - key: SECRET_KEY_BASE
        type: SECRET

      - key: POSTGRES_HOST
        value: ${db.HOSTNAME}

      - key: POSTGRES_PORT
        value: ${db.PORT}

      - key: POSTGRES_DATABASE
        value: ${db.DATABASE}

      - key: POSTGRES_USERNAME
        value: ${db.USERNAME}

      - key: POSTGRES_PASSWORD
        value: ${db.PASSWORD}
        type: SECRET

      - key: REDIS_URL
        value: ${redis.REDIS_URL}

      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
        type: SECRET

databases:
  - name: db
    engine: PG
    production: true
    version: "16"

  - name: redis
    engine: REDIS
    production: true
    version: "7"
