# Path: http/sign.http
# @name LOGIN
POST {{api}}/auth/sign_in
Content-Type: application/json
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
User-Agent-Mobile: Mozilla/5.0 (Linux; Android 4.2.2; GT-I9505 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.59 Mobile Safari/537.36

{
  "email": "{{username_jonh}}",
  "password": "{{password_jonh}}"
}

### 
@token = {{LOGIN.response.headers.Authorization}}

###

# Path: http/inbox-members.http
# @name inbox-members

@accountId = 2
POST {{api}}/api/v1/accounts/{{accountId}}/inbox_members/add
Content-Type: application/json
Authorization: {{token}}

{
    "user_ids": [5],
    "inbox_ids": [2, 3]
}