# Path: http/sign.http
# @name LOGIN
POST {{api}}/auth/sign_in
Content-Type: application/json
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
User-Agent-Mobile: Mozilla/5.0 (Linux; Android 4.2.2; GT-I9505 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.59 Mobile Safari/537.36

{
  "email": "{{username_jonh}}",
  "password": "{{password_jonh}}"
}

### 
@token = {{LOGIN.response.headers.Authorization}}

# Path: http/report.http
# @name reports
@since = 1717556400
@until = 1720148399
@type = account
@business_hours = false
@group_by = day
@account_id = 2

GET {{api}}/api/v2/accounts/{{account_id}}/reports
?metric=triggers
&since={{since}}
&until={{until}}
&type={{type}}
&group_by={{group_by}}
&business_hours={{business_hours}}
Content-Type: application/json
Authorization: {{token}}

### 
@token = {{LOGIN.response.headers.Authorization}}

# Path: http/invoices.http
# @name invoices_report
GET {{api}}/api/v2/accounts/{{account_id}}/reports/invoices
?since={{since}}
&until={{until}}
&business_hours={{business_hours}}
Content-Type: application/json
Authorization: {{token}}

### 

# Path: http/triggers.http
# @name trigger_metrics
GET {{api}}/api/v2/accounts/{{account_id}}/reports/triggers
Content-Type: application/json
Authorization: {{token}}
