# Path: http/sign.http
# @name LOGIN
POST {{api}}/auth/sign_in
Content-Type: application/json
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
User-Agent-Mobile: Mozilla/5.0 (Linux; Android 4.2.2; GT-I9505 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.59 Mobile Safari/537.36

{
  "email": "{{username}}",
  "password": "Password1!"
}

###

# Path: http/summary.http
# @name summary
# http://localhost:3000/api/v2/accounts/5/reports/summary
GET {{api}}/api/v2/accounts/5/reports/summary
?since=1721098800
&until=1721703599
&type=inbox
&id=139
&group_by=day
&business_hours=false
&timezone_offset=-3
&agents_ids[]=63
&agents_ids[]=79
&agents_ids[]=70
&agents_ids[]=61
&agents_ids[]=73
&agents_ids[]=81
&agents_ids[]=64
&agents_ids[]=80
&agents_ids[]=78
&agents_ids[]=6
&agents_ids[]=82
Content-Type: application/json
Authorization: {{token}}

### 
@token = {{LOGIN.response.headers.Authorization}}

# Path: http/report.http
# @name reports
@metric = triggers
@since = 1717556400
@until = 1720148399
@type = account
@business_hours = false
@group_by = day
@account_id = 2

GET {{api}}/api/v2/accounts/{{account_id}}/reports
?metric={{metric}}
&since={{since}}
&until={{until}}
&type={{type}}
&group_by={{group_by}}
&business_hours={{business_hours}}
# &agents_ids[]=1&agents_ids[]=16
&agents_ids[]=198
Content-Type: application/json
Authorization: {{token}}

### 

# Path: http/triggers.http
# @name trigger_metrics
GET {{api}}/api/v2/accounts/{{account_id}}/reports/triggers
Content-Type: application/json
Authorization: {{token}}
