json.name resource.name
json.timezone resource.timezone
json.working_hours resource.weekly_schedule
json.working_hours_enabled resource.working_hours_enabled
json.csat_survey_enabled resource.csat_survey_enabled
json.csat_format resource.csat_format
json.csat_question_text resource.csat_question_text
json.greeting_enabled resource.greeting_enabled
