apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secrets-development
  namespace: chatwoot-development
type: Opaque
data:
  # These will be populated from GitHub Secrets
  SECRET_KEY_BASE: "$(SECRET_KEY_BASE)"
  REDIS_PASSWORD: "$(REDIS_PASSWORD)"
  POSTGRES_PASSWORD: "$(POSTGRES_PASSWORD)"
  # Database credentials
  POSTGRES_USER: "" # Add your base64 encoded database user
  # Mail credentials
  # SMTP Configuration
  SMTP_ADDRESS: "smtp.eu.mailgun.org"
  SMTP_PORT: "2525" 
  SMTP_DOMAIN: "mg.aloochat.ai"
  SMTP_USERNAME: "accounts@mg.aloochat.ai"
  SMTP_PASSWORD: "$(SMTP_PASSWORD)"
  SMTP_AUTHENTICATION: "plain"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
  MAILER_SENDER_EMAIL: "AlooChat Development <accounts@mg.aloochat.ai>"
  SMTP_OPENSSL_VERIFY_MODE: "peer"
  MAILER_INBOUND_EMAIL_DOMAIN: "mg.aloochat.ai"
  RAILS_INBOUND_EMAIL_SERVICE: "mailgun"

  # AlooStudio Configuration
  CLERK_WEBHOOK_SECRET: "$(CLERK_WEBHOOK_SECRET)"
  ALOOSTUDIO_API_TOKEN: "$(ALOOSTUDIO_API_TOKEN)"
  ALOOSTUDIO_WEBHOOK_URL: "$(ALOOSTUDIO_WEBHOOK_URL)"
  ALOOSTUDIO_BACKEND_URL: "$(ALOOSTUDIO_BACKEND_URL)"
  ALOOSTUDIO_FRONTEND_URL: "$(ALOOSTUDIO_FRONTEND_URL)"

  FB_VERIFY_TOKEN: "$(FB_VERIFY_TOKEN)"
  FB_APP_SECRET: "$(FB_APP_SECRET)"
  FB_APP_ID: "$(FB_APP_ID)"
  IG_VERIFY_TOKEN: "$(IG_VERIFY_TOKEN)"
  INSTAGRAM_APP_ID: "$(INSTAGRAM_APP_ID)"

  # Google Configuration
  GOOGLE_OAUTH_CLIENT_ID: "$(GOOGLE_OAUTH_CLIENT_ID)"
  GOOGLE_OAUTH_CLIENT_SECRET: "$(GOOGLE_OAUTH_CLIENT_SECRET)"
  GOOGLE_OAUTH_CALLBACK_URL: "$(GOOGLE_OAUTH_CALLBACK_URL)"
  
  IP_LOOKUP_API_KEY: "$(IP_LOOKUP_API_KEY)"

  RAILS_INBOUND_EMAIL_PASSWORD: "$(RAILS_INBOUND_EMAIL_PASSWORD)"
  MAILGUN_INGRESS_SIGNING_KEY: "$(MAILGUN_INGRESS_SIGNING_KEY)"
  PAYZAH_API_URL: "$(PAYZAH_API_URL)"
  ENABLE_PUSH_RELAY_SERVER: "$(ENABLE_PUSH_RELAY_SERVER)"
  APPSIGNAL_PUSH_API_KEY: "$(APPSIGNAL_PUSH_API_KEY)"
  APPSIGNAL_APP_NAME: "$(APPSIGNAL_APP_NAME)"
  POSTHOG_API_KEY: "$(POSTHOG_API_KEY)"
  POSTHOG_API_HOST: "$(POSTHOG_API_HOST)"
