apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: chatwoot
  labels:
    app.kubernetes.io/name: chatwoot
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard   # descomenta y ajusta según tu cluster
