default: &default
  adapter: postgresql
  encoding: unicode

  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

  sslmode: <%= ENV.fetch('POSTGRES_SSLMODE', 'disable') %>

  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>

  reaping_frequency: <%= ENV.fetch('DB_POOL_REAPING_FREQUENCY', 30) %>

  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '14s') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_dev') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_production') %>