const {
  blue,
  blueDark,
  green,
  greenDark,
  yellow,
  yellowDark,
  slate,
  slateDark,
  red,
  redDark,
  violet,
  violetDark,
} = require('@radix-ui/colors');

export const colors = {
  woot: {
    25: '#f9f9f9',
    50: '#f2f2f2',
    75: '#ebebeb',
    100: '#dfdfdf',
    200: '#bfbfbf',
    300: '#a4a4a4',
    400: '#aeaeae',
    500: '#909090',
    600: '#797979',
    700: '#666666',
    800: '#444444',
    900: '#181818',
  },
  green: {
    50: '#e1e1e1',
    100: '#d1d1d1',
    200: '#bebebe',
    300: '#a2a2a2',
    400: '#919191',
    500: '#878787',
    600: '#7f7f7f',
    700: '#6b6b6b',
    800: '#585858',
    900: '#4a4a4a',
  },
  yellow: {
    50: '#fbfbfb',
    100: '#f6f6f6',
    200: '#e4e4e4',
    300: '#f3f3f3',
    400: '#dedede',
    500: '#dadada',
    600: '#aeaeae',
    700: '#535353',
    800: '#181818',
    900: '#121212',
  },
  slate: {
    25: '#f9f9f9',
    50: '#f0f0f0',
    75: '#e8e8e8',
    100: '#e1e1e1',
    200: '#cecece',
    300: '#bbbbbb',
    400: '#b4b4b4',
    500: '#7b7b7b',
    600: '#646464',
    700: '#606060',
    800: '#2a2a2a',
    900: '#111111',
  },
  black: {
    50: '#f9f9f9',
    100: '#eeeeee',
    200: '#cecece',
    300: '#bbbbbb',
    400: '#b4b4b4',
    500: '#8d8d8d',
    600: '#6e6e6e',
    700: '#606060',
    800: '#474747',
    900: '#191919',
  },
  red: {
    50: '#dbdbdb',
    100: '#cbcbcb',
    200: '#a2a2a2',
    300: '#ababab',
    400: '#7b7b7b',
    500: '#6a6a6a',
    600: '#606060',
    700: '#4f4f4f',
    800: '#5d5d5d',
    900: '#282828',
  },
  violet: {
    50: '#fcfcfc',
    100: '#e0e0e0',
    200: '#d0d0d0',
    300: '#a3a3a3',
    400: '#5c5c5c',
    500: '#646464',
    600: '#626262',
    700: '#4e4e4e',
    800: '#404040',
    900: '#2c2c2c',
  },

  // next design system color
  n: {
    slate: {
      1: 'rgb(var(--slate-1) / <alpha-value>)',
      2: 'rgb(var(--slate-2) / <alpha-value>)',
      3: 'rgb(var(--slate-3) / <alpha-value>)',
      4: 'rgb(var(--slate-4) / <alpha-value>)',
      5: 'rgb(var(--slate-5) / <alpha-value>)',
      6: 'rgb(var(--slate-6) / <alpha-value>)',
      7: 'rgb(var(--slate-7) / <alpha-value>)',
      8: 'rgb(var(--slate-8) / <alpha-value>)',
      9: 'rgb(var(--slate-9) / <alpha-value>)',
      10: 'rgb(var(--slate-10) / <alpha-value>)',
      11: 'rgb(var(--slate-11) / <alpha-value>)',
      12: 'rgb(var(--slate-12) / <alpha-value>)',
    },

    iris: {
      1: 'rgb(var(--iris-1) / <alpha-value>)',
      2: 'rgb(var(--iris-2) / <alpha-value>)',
      3: 'rgb(var(--iris-3) / <alpha-value>)',
      4: 'rgb(var(--iris-4) / <alpha-value>)',
      5: 'rgb(var(--iris-5) / <alpha-value>)',
      6: 'rgb(var(--iris-6) / <alpha-value>)',
      7: 'rgb(var(--iris-7) / <alpha-value>)',
      8: 'rgb(var(--iris-8) / <alpha-value>)',
      9: 'rgb(var(--iris-9) / <alpha-value>)',
      10: 'rgb(var(--iris-10) / <alpha-value>)',
      11: 'rgb(var(--iris-11) / <alpha-value>)',
      12: 'rgb(var(--iris-12) / <alpha-value>)',
    },

    blue: {
      1: 'rgb(var(--blue-1) / <alpha-value>)',
      2: 'rgb(var(--blue-2) / <alpha-value>)',
      3: 'rgb(var(--blue-3) / <alpha-value>)',
      4: 'rgb(var(--blue-4) / <alpha-value>)',
      5: 'rgb(var(--blue-5) / <alpha-value>)',
      6: 'rgb(var(--blue-6) / <alpha-value>)',
      7: 'rgb(var(--blue-7) / <alpha-value>)',
      8: 'rgb(var(--blue-8) / <alpha-value>)',
      9: 'rgb(var(--blue-9) / <alpha-value>)',
      10: 'rgb(var(--blue-10) / <alpha-value>)',
      11: 'rgb(var(--blue-11) / <alpha-value>)',
      12: 'rgb(var(--blue-12) / <alpha-value>)',
    },

    ruby: {
      1: 'rgb(var(--ruby-1) / <alpha-value>)',
      2: 'rgb(var(--ruby-2) / <alpha-value>)',
      3: 'rgb(var(--ruby-3) / <alpha-value>)',
      4: 'rgb(var(--ruby-4) / <alpha-value>)',
      5: 'rgb(var(--ruby-5) / <alpha-value>)',
      6: 'rgb(var(--ruby-6) / <alpha-value>)',
      7: 'rgb(var(--ruby-7) / <alpha-value>)',
      8: 'rgb(var(--ruby-8) / <alpha-value>)',
      9: 'rgb(var(--ruby-9) / <alpha-value>)',
      10: 'rgb(var(--ruby-10) / <alpha-value>)',
      11: 'rgb(var(--ruby-11) / <alpha-value>)',
      12: 'rgb(var(--ruby-12) / <alpha-value>)',
    },

    amber: {
      1: 'rgb(var(--amber-1) / <alpha-value>)',
      2: 'rgb(var(--amber-2) / <alpha-value>)',
      3: 'rgb(var(--amber-3) / <alpha-value>)',
      4: 'rgb(var(--amber-4) / <alpha-value>)',
      5: 'rgb(var(--amber-5) / <alpha-value>)',
      6: 'rgb(var(--amber-6) / <alpha-value>)',
      7: 'rgb(var(--amber-7) / <alpha-value>)',
      8: 'rgb(var(--amber-8) / <alpha-value>)',
      9: 'rgb(var(--amber-9) / <alpha-value>)',
      10: 'rgb(var(--amber-10) / <alpha-value>)',
      11: 'rgb(var(--amber-11) / <alpha-value>)',
      12: 'rgb(var(--amber-12) / <alpha-value>)',
    },

    teal: {
      1: 'rgb(var(--teal-1) / <alpha-value>)',
      2: 'rgb(var(--teal-2) / <alpha-value>)',
      3: 'rgb(var(--teal-3) / <alpha-value>)',
      4: 'rgb(var(--teal-4) / <alpha-value>)',
      5: 'rgb(var(--teal-5) / <alpha-value>)',
      6: 'rgb(var(--teal-6) / <alpha-value>)',
      7: 'rgb(var(--teal-7) / <alpha-value>)',
      8: 'rgb(var(--teal-8) / <alpha-value>)',
      9: 'rgb(var(--teal-9) / <alpha-value>)',
      10: 'rgb(var(--teal-10) / <alpha-value>)',
      11: 'rgb(var(--teal-11) / <alpha-value>)',
      12: 'rgb(var(--teal-12) / <alpha-value>)',
    },

    gray: {
      1: 'rgb(var(--gray-1) / <alpha-value>)',
      2: 'rgb(var(--gray-2) / <alpha-value>)',
      3: 'rgb(var(--gray-3) / <alpha-value>)',
      4: 'rgb(var(--gray-4) / <alpha-value>)',
      5: 'rgb(var(--gray-5) / <alpha-value>)',
      6: 'rgb(var(--gray-6) / <alpha-value>)',
      7: 'rgb(var(--gray-7) / <alpha-value>)',
      8: 'rgb(var(--gray-8) / <alpha-value>)',
      9: 'rgb(var(--gray-9) / <alpha-value>)',
      10: 'rgb(var(--gray-10) / <alpha-value>)',
      11: 'rgb(var(--gray-11) / <alpha-value>)',
      12: 'rgb(var(--gray-12) / <alpha-value>)',
    },

    violet: {
      1: 'rgb(var(--violet-1) / <alpha-value>)',
      2: 'rgb(var(--violet-2) / <alpha-value>)',
      3: 'rgb(var(--violet-3) / <alpha-value>)',
      4: 'rgb(var(--violet-4) / <alpha-value>)',
      5: 'rgb(var(--violet-5) / <alpha-value>)',
      6: 'rgb(var(--violet-6) / <alpha-value>)',
      7: 'rgb(var(--violet-7) / <alpha-value>)',
      8: 'rgb(var(--violet-8) / <alpha-value>)',
      9: 'rgb(var(--violet-9) / <alpha-value>)',
      10: 'rgb(var(--violet-10) / <alpha-value>)',
      11: 'rgb(var(--violet-11) / <alpha-value>)',
      12: 'rgb(var(--violet-12) / <alpha-value>)',
    },

    black: '#000000',
    brand: '#6b6e76',
    portal: 'var(--dynamic-portal-color)',
    'portal-soft': 'var(--dynamic-portal-color-soft)',
    'portal-faint': 'var(--dynamic-portal-color-faint)',
    background: 'rgb(var(--background-color) / <alpha-value>)',
    'input-background': 'rgba(var(--background-input-box))',
    surface: {
      1: 'rgb(var(--surface-1) / <alpha-value>)',
      2: 'rgb(var(--surface-2) / <alpha-value>)',
      active: 'rgb(var(--surface-active) / <alpha-value>)',
    },
    solid: {
      1: 'rgb(var(--solid-1) / <alpha-value>)',
      2: 'rgb(var(--solid-2) / <alpha-value>)',
      3: 'rgb(var(--solid-3) / <alpha-value>)',
      active: 'rgb(var(--solid-active) / <alpha-value>)',
      amber: 'rgb(var(--solid-amber) / <alpha-value>)',
      'amber-button': 'rgb(var(--solid-amber-button) / <alpha-value>)',
      blue: 'rgb(var(--solid-blue) / <alpha-value>)',
      'blue-2': 'rgb(var(--solid-blue-2) / <alpha-value>)',
      red: 'rgb(var(--solid-red) / <alpha-value>)',
      iris: 'rgb(var(--solid-iris) / <alpha-value>)',
      purple: 'rgb(var(--solid-purple) / <alpha-value>)',
    },
    alpha: {
      1: 'rgba(var(--alpha-1))',
      2: 'rgba(var(--alpha-2))',
      3: 'rgba(var(--alpha-3))',
      black1: 'rgba(var(--black-alpha-1))',
      black2: 'rgba(var(--black-alpha-2))',
      white: 'rgba(var(--white-alpha))',
    },
    // Voice call widget
    'call-widget': 'rgba(var(--call-widget))',
    'call-widget-border': 'rgba(var(--call-widget-border))',
    'call-widget-text': 'rgba(var(--call-widget-text))',
    'call-widget-sub-text': 'rgba(var(--call-widget-sub-text))',
    // Border colors
    weak: 'rgb(var(--border-weak) / <alpha-value>)',
    container: 'rgba(var(--border-container))',
    strong: 'rgb(var(--border-strong) / <alpha-value>)',
    'blue-strong': 'rgb(var(--border-blue-strong) / <alpha-value>)',
    'blue-border': 'rgba(var(--border-blue))',
    // Text colors
    'blue-text': 'rgb(var(--text-blue) / <alpha-value>)',
    'purple-text': 'rgb(var(--text-purple) / <alpha-value>)',
    'amber-text': 'rgb(var(--text-amber) / <alpha-value>)',
    card: 'rgb(var(--card-color) / <alpha-value>)',
    overlay: {
      default: 'rgba(var(--overlay))',
      avatar: 'rgba(var(--overlay-avatar))',
    },
    button: {
      color: 'rgb(var(--button-color) / <alpha-value>)',
      hover: 'rgb(var(--button-hover-color) / <alpha-value>)',
    },
    label: {
      color: 'rgb(var(--label-background) / <alpha-value>)',
      border: 'rgba(var(--label-border))',
    },
  },
};
