export default [
  {
    id: 12,
    content:
      'This tutorial will show you how to use Chatwoot and, hence, ensure you practice effective customer communication. We will explain in detail the following:\n\n* Step-by-step setup of your account, with illustrative screenshots.\n\n* An in-depth explanation of all the core features of Chatwoot.\n\n* Get your account up and running by the end of this tutorial.\n\n* Basic concepts of customer communication.',
    accountId: null,
    contactId: null,
    user: {
      id: 30,
      account_id: 2,
      availability_status: 'offline',
      auto_offline: true,
      confirmed: true,
      email: 'bruce@paperlayer.test',
      available_name: 'Bruce',
      name: 'Bruce',
      role: 'administrator',
      thumbnail:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--515dbb35e9ba3c36d14f4c4b77220a675513c1fb/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/2.jpg',
      custom_role_id: null,
    },
    createdAt: 1730786556,
    updatedAt: 1730786556,
  },
  {
    id: 10,
    content:
      'We discussed a couple of things:\n\n* Product offering and how it can be useful to talk with people.\n\n* They’ll reach out to us after an internal review.',
    accountId: null,
    contactId: null,
    user: {
      id: 1,
      account_id: 2,
      availability_status: 'online',
      auto_offline: false,
      confirmed: true,
      email: 'hillary@chatwoot.com',
      available_name: 'Hillary',
      name: 'Hillary',
      role: 'administrator',
      thumbnail: '',
      custom_role_id: null,
    },
    createdAt: 1730782566,
    updatedAt: 1730782566,
  },
  {
    id: 9,
    content:
      'We discussed a couple of things:\n\n* Product offering and how it can be useful to talk with people.\n\n* They’ll reach out to us after an internal review.',
    accountId: null,
    contactId: null,
    user: {
      id: 1,
      account_id: 2,
      availability_status: 'online',
      auto_offline: false,
      confirmed: true,
      email: 'john@chatwoot.com',
      available_name: 'John',
      name: 'John',
      role: 'administrator',
      thumbnail: '',
      custom_role_id: null,
    },
    createdAt: 1730782564,
    updatedAt: 1730782564,
  },
];
