<script setup>
import InboxList from './InboxList.vue';
import InboxItemHeader from './components/InboxItemHeader.vue';
import ConversationBox from 'dashboard/components/widgets/conversation/ConversationBox.vue';

const notifications = [
  {
    id: 8314,
    notification_type: 'participating_conversation_new_message',
    push_message_title: '[New message] - #141 erer',
    primary_actor_type: 'Conversation',
    primary_actor_id: 3257,
    primary_actor: {
      additional_attributes: {
        browser: {
          device_name: 'Unknown',
          browser_name: 'Chrome',
          platform_name: 'macOS',
          browser_version: '120.0.0.0',
          platform_version: '10.15.7',
        },
        referer: 'http://localhost:3000/widget_tests?dark_mode=auto',
        initiated_at: {
          timestamp: 'Thu Jan 11 2024 11:34:05 GMT+0530 (India Standard Time)',
        },
        browser_language: 'en',
      },
      can_reply: true,
      channel: 'Channel::WebWidget',
      contact_inbox: {
        id: 5255,
        contact_id: 5217,
        inbox_id: 242,
        source_id: 'd702ce6c-b546-46c1-92a8-5d0aac836f7a',
        created_at: '2024-01-11T05:55:24.011Z',
        updated_at: '2024-01-11T05:55:24.011Z',
        hmac_verified: false,
        pubsub_token: 'M3SQCdcxD5thapU9TsKpx6QG',
      },
      id: 141,
      inbox_id: 242,
      messages: [
        {
          id: 17448,
          content: 'erer',
          account_id: 66,
          inbox_id: 242,
          conversation_id: 141,
          message_type: 0,
          created_at: 1704953081,
          updated_at: '2024-01-11T06:04:41.745Z',
          private: false,
          status: 'sent',
          source_id: null,
          content_type: 'text',
          content_attributes: {
            in_reply_to: null,
          },
          sender_type: 'Contact',
          sender_id: 5217,
          external_source_ids: {},
          additional_attributes: {},
          processed_message_content: 'erer',
          sentiment: {},
          conversation: {
            assignee_id: 52,
            unread_count: 0,
            last_activity_at: 1704953081,
            contact_inbox: {
              source_id: 'd702ce6c-b546-46c1-92a8-5d0aac836f7a',
            },
          },
          sender: {
            additional_attributes: {
              city: '',
              country: '',
              description: '',
              company_name: '',
              country_code: '',
              created_at_ip: '::1',
              social_profiles: {
                github: '',
                twitter: '',
                facebook: '',
                linkedin: '',
                instagram: '',
              },
            },
            custom_attributes: {},
            email: null,
            id: 5217,
            identifier: null,
            name: 'James',
            phone_number: '+918747477333',
            thumbnail: '',
            type: 'contact',
          },
        },
      ],
      labels: [],
      meta: {
        sender: {
          additional_attributes: {
            city: '',
            country: '',
            description: '',
            company_name: '',
            country_code: '',
            created_at_ip: '::1',
            social_profiles: {
              github: '',
              twitter: '',
              facebook: '',
              linkedin: '',
              instagram: '',
            },
          },
          custom_attributes: {},
          email: null,
          id: 5217,
          identifier: null,
          name: 'James',
          phone_number: '+918747477333',
          thumbnail: '',
          type: 'contact',
        },
        assignee: {
          id: 52,
          name: 'Sivin Varghese',
          available_name: 'Sivin Varghese',
          avatar_url:
            'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
          type: 'user',
          availability_status: 'offline',
          thumbnail:
            'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
        },
        team: null,
        hmac_verified: false,
      },
      status: 'open',
      custom_attributes: {},
      snoozed_until: null,
      unread_count: 0,
      first_reply_created_at: '2024-01-11T06:04:11.077Z',
      priority: 'urgent',
      waiting_since: 1704953061,
      agent_last_seen_at: 1705909598,
      contact_last_seen_at: 1704953081,
      timestamp: 1704953081,
      created_at: 1704953045,
    },
    read_at: null,
    secondary_actor: {
      id: 17448,
      content: 'erer',
      account_id: 66,
      inbox_id: 242,
      conversation_id: 141,
      message_type: 0,
      created_at: 1704953081,
      updated_at: '2024-01-11T06:04:41.745Z',
      private: false,
      status: 'sent',
      source_id: null,
      content_type: 'text',
      content_attributes: {
        in_reply_to: null,
      },
      sender_type: 'Contact',
      sender_id: 5217,
      external_source_ids: {},
      additional_attributes: {},
      processed_message_content: 'erer',
      sentiment: {},
      conversation: {
        assignee_id: 52,
        unread_count: 0,
        last_activity_at: 1704953081,
        contact_inbox: {
          source_id: 'd702ce6c-b546-46c1-92a8-5d0aac836f7a',
        },
      },
      sender: {
        additional_attributes: {
          city: '',
          country: '',
          description: '',
          company_name: '',
          country_code: '',
          created_at_ip: '::1',
          social_profiles: {
            github: '',
            twitter: '',
            facebook: '',
            linkedin: '',
            instagram: '',
          },
        },
        custom_attributes: {},
        email: null,
        id: 5217,
        identifier: null,
        name: 'James',
        phone_number: '+918747477333',
        thumbnail: '',
        type: 'contact',
      },
    },
    user: {
      id: 52,
      name: 'Sivin Varghese',
      available_name: 'Sivin Varghese',
      avatar_url:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
      type: 'user',
      availability_status: 'offline',
      thumbnail:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
    },
    created_at: 1704953081,
    last_activity_at: 1704953081,
  },
  {
    id: 8303,
    notification_type: 'participating_conversation_new_message',
    push_message_title: '[New message] - #140 we',
    primary_actor_type: 'Conversation',
    primary_actor_id: 3256,
    primary_actor: {
      additional_attributes: {
        browser: {
          device_name: 'Unknown',
          browser_name: 'Chrome',
          platform_name: 'macOS',
          browser_version: '120.0.0.0',
          platform_version: '10.15.7',
        },
        referer: 'http://localhost:3000/widget_tests?dark_mode=auto',
        initiated_at: {
          timestamp: 'Tue Jan 09 2024 13:45:47 GMT+0530 (India Standard Time)',
        },
        browser_language: 'en',
      },
      can_reply: true,
      channel: 'Channel::WebWidget',
      contact_inbox: {
        id: 5254,
        contact_id: 5216,
        inbox_id: 242,
        source_id: '96544547-39c9-4977-b991-7ee707c664cd',
        created_at: '2024-01-09T03:02:21.898Z',
        updated_at: '2024-01-09T03:02:21.898Z',
        hmac_verified: false,
        pubsub_token: 'EPkRhm7bT7VtE1ELwH9V8EBy',
      },
      id: 140,
      inbox_id: 242,
      messages: [
        {
          id: 17430,
          content: 'we',
          account_id: 66,
          inbox_id: 242,
          conversation_id: 140,
          message_type: 0,
          created_at: 1704789302,
          updated_at: '2024-01-09T08:35:02.433Z',
          private: false,
          status: 'sent',
          source_id: null,
          content_type: 'text',
          content_attributes: {
            in_reply_to: null,
          },
          sender_type: 'Contact',
          sender_id: 5216,
          external_source_ids: {},
          additional_attributes: {},
          processed_message_content: 'we',
          sentiment: {},
          conversation: {
            assignee_id: null,
            unread_count: 0,
            last_activity_at: 1704789302,
            contact_inbox: {
              source_id: '96544547-39c9-4977-b991-7ee707c664cd',
            },
          },
          sender: {
            additional_attributes: {
              created_at_ip: '::1',
            },
            custom_attributes: {},
            email: null,
            id: 5216,
            identifier: null,
            name: 'Same same',
            phone_number: null,
            thumbnail: '',
            type: 'contact',
          },
        },
      ],
      labels: [],
      meta: {
        sender: {
          additional_attributes: {
            created_at_ip: '::1',
          },
          custom_attributes: {},
          email: null,
          id: 5216,
          identifier: null,
          name: 'Same same',
          phone_number: null,
          thumbnail: '',
          type: 'contact',
        },
        assignee: null,
        team: null,
        hmac_verified: false,
      },
      status: 'pending',
      custom_attributes: {},
      snoozed_until: null,
      unread_count: 0,
      first_reply_created_at: '2024-01-09T08:21:52.150Z',
      priority: 'high',
      waiting_since: 1704788514,
      agent_last_seen_at: 1704789675,
      contact_last_seen_at: 1704789302,
      timestamp: 1704789302,
      created_at: 1704788148,
    },
    read_at: null,
    secondary_actor: {
      id: 17430,
      content: 'we',
      account_id: 66,
      inbox_id: 242,
      conversation_id: 140,
      message_type: 0,
      created_at: 1704789302,
      updated_at: '2024-01-09T08:35:02.433Z',
      private: false,
      status: 'sent',
      source_id: null,
      content_type: 'text',
      content_attributes: {
        in_reply_to: null,
      },
      sender_type: 'Contact',
      sender_id: 5216,
      external_source_ids: {},
      additional_attributes: {},
      processed_message_content: 'we',
      sentiment: {},
      conversation: {
        assignee_id: null,
        unread_count: 0,
        last_activity_at: 1704789302,
        contact_inbox: {
          source_id: '96544547-39c9-4977-b991-7ee707c664cd',
        },
      },
      sender: {
        additional_attributes: {
          created_at_ip: '::1',
        },
        custom_attributes: {},
        email: null,
        id: 5216,
        identifier: null,
        name: 'Same same',
        phone_number: null,
        thumbnail: '',
        type: 'contact',
      },
    },
    user: {
      id: 52,
      name: 'Sivin Varghese',
      available_name: 'Sivin Varghese',
      avatar_url:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
      type: 'user',
      availability_status: 'offline',
      thumbnail:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
    },
    created_at: 1704789302,
    last_activity_at: 1704789302,
  },
  {
    id: 8238,
    notification_type: 'participating_conversation_new_message',
    push_message_title: '[New message] - #137 wer',
    primary_actor_type: 'Conversation',
    primary_actor_id: 3253,
    primary_actor: {
      additional_attributes: {
        browser: {
          device_name: 'Unknown',
          browser_name: 'Chrome',
          platform_name: 'macOS',
          browser_version: '120.0.0.0',
          platform_version: '10.15.7',
        },
        referer: 'http://localhost:3000/widget_tests?dark_mode=auto',
        initiated_at: {
          timestamp: 'Fri Jan 05 2024 15:21:52 GMT+0530 (India Standard Time)',
        },
        browser_language: 'en',
      },
      can_reply: true,
      channel: 'Channel::WebWidget',
      contact_inbox: {
        id: 5251,
        contact_id: 5213,
        inbox_id: 242,
        source_id: 'b6946df1-1dd1-4c85-b9f1-a51dcc16b94d',
        created_at: '2024-01-05T09:27:38.929Z',
        updated_at: '2024-01-05T09:27:38.929Z',
        hmac_verified: false,
        pubsub_token: 'yka83n8ipwKBPyt4Q6mTw2aw',
      },
      id: 137,
      inbox_id: 242,
      messages: [
        {
          id: 17432,
          content:
            '**`\\r\\n\\r\\nChristmas \\u0026 New Year\\r\\n\\r\\nWe are now closed for the Christmas holidays.  We will be back between the 27 December to the 29 December and then business as usual from 2 January.\\r\\n\\r\\n`**`\\r\\n\\r\\nOur support team is currently unavailable. \\r\\n\\r\\nOur support hours are 9am-4pm Monday to Thursday and Friday 9am-12pm\\r\\n\\r\\nPlease send your name and contact information and one of our team will get back to you as soon as possible.\\r\\n\\r\\nThanks,\\r\\n\\r\\nMy Pet Walker Support`',
          account_id: 66,
          inbox_id: 242,
          conversation_id: 137,
          message_type: 1,
          created_at: 1704864064,
          updated_at: '2024-01-10T05:21:04.943Z',
          private: false,
          status: 'sent',
          source_id: null,
          content_type: 'text',
          content_attributes: {},
          sender_type: 'User',
          sender_id: 52,
          external_source_ids: {},
          additional_attributes: {},
          processed_message_content:
            '**`\\r\\n\\r\\nChristmas \\u0026 New Year\\r\\n\\r\\nWe are now closed for the Christmas holidays.  We will be back between the 27 December to the 29 December and then business as usual from 2 January.\\r\\n\\r\\n`**`\\r\\n\\r\\nOur support team is currently unavailable. \\r\\n\\r\\nOur support hours are 9am-4pm Monday to Thursday and Friday 9am-12pm\\r\\n\\r\\nPlease send your name and contact information and one of our team will get back to you as soon as possible.\\r\\n\\r\\nThanks,\\r\\n\\r\\nMy Pet Walker Support`',
          sentiment: {},
          conversation: {
            assignee_id: 52,
            unread_count: 0,
            last_activity_at: 1704864064,
            contact_inbox: {
              source_id: 'b6946df1-1dd1-4c85-b9f1-a51dcc16b94d',
            },
          },
          sender: {
            id: 52,
            name: 'Sivin Varghese',
            available_name: 'Sivin Varghese',
            avatar_url:
              'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
            type: 'user',
            availability_status: 'offline',
            thumbnail:
              'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
          },
        },
      ],
      labels: [],
      meta: {
        sender: {
          additional_attributes: {
            city: '',
            country: '',
            description: '',
            company_name: '',
            country_code: '',
            created_at_ip: '::1',
            social_profiles: {
              github: '',
              twitter: '',
              facebook: '',
              linkedin: '',
              instagram: '',
            },
          },
          custom_attributes: {},
          email: null,
          id: 5213,
          identifier: null,
          name: 'Sanju',
          phone_number: '+9284774747574',
          thumbnail: '',
          type: 'contact',
        },
        assignee: {
          id: 52,
          name: 'Sivin Varghese',
          available_name: 'Sivin Varghese',
          avatar_url:
            'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
          type: 'user',
          availability_status: 'offline',
          thumbnail:
            'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
        },
        team: null,
        hmac_verified: false,
      },
      status: 'snoozed',
      custom_attributes: {},
      snoozed_until: null,
      unread_count: 0,
      first_reply_created_at: '2024-01-05T09:52:02.991Z',
      priority: 'medium',
      waiting_since: 0,
      agent_last_seen_at: 1705663077,
      contact_last_seen_at: 1704725768,
      timestamp: 1704864064,
      created_at: 1704448312,
    },
    read_at: '2024-01-08T14:56:12.135Z',
    secondary_actor: {
      id: 17357,
      content: 'wer',
      account_id: 66,
      inbox_id: 242,
      conversation_id: 137,
      message_type: 0,
      created_at: 1704725768,
      updated_at: '2024-01-08T14:56:08.855Z',
      private: false,
      status: 'sent',
      source_id: null,
      content_type: 'text',
      content_attributes: {
        in_reply_to: null,
      },
      sender_type: 'Contact',
      sender_id: 5213,
      external_source_ids: {},
      additional_attributes: {},
      processed_message_content: 'wer',
      sentiment: {},
      conversation: {
        assignee_id: 52,
        unread_count: 0,
        last_activity_at: 1704864064,
        contact_inbox: {
          source_id: 'b6946df1-1dd1-4c85-b9f1-a51dcc16b94d',
        },
      },
      sender: {
        additional_attributes: {
          city: '',
          country: '',
          description: '',
          company_name: '',
          country_code: '',
          created_at_ip: '::1',
          social_profiles: {
            github: '',
            twitter: '',
            facebook: '',
            linkedin: '',
            instagram: '',
          },
        },
        custom_attributes: {},
        email: null,
        id: 5213,
        identifier: null,
        name: 'Sanju',
        phone_number: '+9284774747574',
        thumbnail: '',
        type: 'contact',
      },
    },
    user: {
      id: 52,
      name: 'Sivin Varghese',
      available_name: 'Sivin Varghese',
      avatar_url:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
      type: 'user',
      availability_status: 'offline',
      thumbnail:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
    },
    created_at: 1704725768,
    last_activity_at: 1704725768,
  },
  {
    id: 8226,
    notification_type: 'participating_conversation_new_message',
    push_message_title: '[New message] - #139 wer',
    primary_actor_type: 'Conversation',
    primary_actor_id: 3255,
    primary_actor: {
      additional_attributes: {
        browser: {
          device_name: 'Unknown',
          browser_name: 'Chrome',
          platform_name: 'macOS',
          browser_version: '120.0.0.0',
          platform_version: '10.15.7',
        },
        referer:
          'https://sivin-tunnel.chatwoot.dev/widget_tests?dark_mode=auto',
        initiated_at: {
          timestamp: 'Mon Jan 08 2024 19:59:34 GMT+0530 (India Standard Time)',
        },
        browser_language: 'en',
      },
      can_reply: true,
      channel: 'Channel::WebWidget',
      contact_inbox: {
        id: 5253,
        contact_id: 5215,
        inbox_id: 242,
        source_id: '4767e8ac-4e92-417e-9e92-70a3c7fa5065',
        created_at: '2024-01-08T14:29:18.331Z',
        updated_at: '2024-01-08T14:29:18.331Z',
        hmac_verified: false,
        pubsub_token: '4wrMXGUM5E779KuNJk5RxBM7',
      },
      id: 139,
      inbox_id: 242,
      messages: [
        {
          id: 17344,
          content: 'wer',
          account_id: 66,
          inbox_id: 242,
          conversation_id: 139,
          message_type: 0,
          created_at: 1704724187,
          updated_at: '2024-01-08T14:29:47.919Z',
          private: false,
          status: 'sent',
          source_id: null,
          content_type: 'text',
          content_attributes: {
            in_reply_to: null,
          },
          sender_type: 'Contact',
          sender_id: 5215,
          external_source_ids: {},
          additional_attributes: {},
          processed_message_content: 'wer',
          sentiment: {},
          conversation: {
            assignee_id: null,
            unread_count: 3,
            last_activity_at: 1704724187,
            contact_inbox: {
              source_id: '4767e8ac-4e92-417e-9e92-70a3c7fa5065',
            },
          },
          sender: {
            additional_attributes: {
              created_at_ip: '2001:df5:2380:5012:d98a:b03f:354e:f145',
            },
            custom_attributes: {},
            email: null,
            id: 5215,
            identifier: null,
            name: 'Nithin',
            phone_number: null,
            thumbnail: '',
            type: 'contact',
          },
        },
      ],
      labels: [],
      meta: {
        sender: {
          additional_attributes: {
            created_at_ip: '2001:df5:2380:5012:d98a:b03f:354e:f145',
          },
          custom_attributes: {},
          email: null,
          id: 5215,
          identifier: null,
          name: 'Nithin',
          phone_number: null,
          thumbnail: '',
          type: 'contact',
        },
        assignee: null,
        team: null,
        hmac_verified: false,
      },
      status: 'resolved',
      custom_attributes: {},
      snoozed_until: null,
      unread_count: 3,
      first_reply_created_at: null,
      priority: 'low',
      waiting_since: 1704724174,
      agent_last_seen_at: 1704724181,
      contact_last_seen_at: 1704724188,
      timestamp: 1704724187,
      created_at: 1704724174,
    },
    read_at: null,
    secondary_actor: {
      id: 17344,
      content: 'wer',
      account_id: 66,
      inbox_id: 242,
      conversation_id: 139,
      message_type: 0,
      created_at: 1704724187,
      updated_at: '2024-01-08T14:29:47.919Z',
      private: false,
      status: 'sent',
      source_id: null,
      content_type: 'text',
      content_attributes: {
        in_reply_to: null,
      },
      sender_type: 'Contact',
      sender_id: 5215,
      external_source_ids: {},
      additional_attributes: {},
      processed_message_content: 'wer',
      sentiment: {},
      conversation: {
        assignee_id: null,
        unread_count: 3,
        last_activity_at: 1704724187,
        contact_inbox: {
          source_id: '4767e8ac-4e92-417e-9e92-70a3c7fa5065',
        },
      },
      sender: {
        additional_attributes: {
          created_at_ip: '2001:df5:2380:5012:d98a:b03f:354e:f145',
        },
        custom_attributes: {},
        email: null,
        id: 5215,
        identifier: null,
        name: 'Nithin',
        phone_number: null,
        thumbnail: '',
        type: 'contact',
      },
    },
    user: {
      id: 52,
      name: 'Sivin Varghese',
      available_name: 'Sivin Varghese',
      avatar_url:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
      type: 'user',
      availability_status: 'offline',
      thumbnail:
        'https://sivin-tunnel.chatwoot.dev/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bdcbe4a44caf280194314c3dcd7bf80fb48455c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--df796c2af3c0153e55236c2f3cf3a199ac2cb6f7/44.jpg',
    },
    created_at: 1704724187,
    last_activity_at: 1704724187,
  },
];
</script>
<template>
  <section class="flex w-full h-full bg-white dark:bg-slate-900">
    <InboxList :notifications="notifications" />
    <div class="flex flex-col w-full h-full">
      <InboxItemHeader :total-length="28" :current-index="1" />
      <ConversationBox class="h-full" />
    </div>
  </section>
</template>
