# Chatwoot's per-row display_id is generated by database triggers that own a
# per-account sequence (conv_dpid_seq_<account_id> for conversations,
# camp_dpid_seq_<account_id> for campaigns). The original schema was loaded from
# db/schema.rb, which cannot represent triggers, so these triggers (and the
# per-account sequences they lazily create) were never created in the live
# database. That made every conversation/campaign insert fail with a NOT NULL
# violation on display_id.
#
# This migration recreates the four triggers and backfills the per-account
# sequences for every existing account so new inserts work and the sequence
# starts above any display_id already in use.
class RecreateDisplayIdTriggers < ActiveRecord::Migration[7.0]
  def up
    # --- Trigger functions ------------------------------------------------
    execute <<~SQL
      CREATE OR REPLACE FUNCTION create_conv_dpid_seq() RETURNS trigger AS $$
      BEGIN
        EXECUTE format('CREATE SEQUENCE IF NOT EXISTS conv_dpid_seq_%s', NEW.id);
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    SQL

    execute <<~SQL
      CREATE OR REPLACE FUNCTION set_conv_display_id() RETURNS trigger AS $$
      BEGIN
        NEW.display_id := nextval('conv_dpid_seq_' || NEW.account_id);
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    SQL

    execute <<~SQL
      CREATE OR REPLACE FUNCTION create_camp_dpid_seq() RETURNS trigger AS $$
      BEGIN
        EXECUTE format('CREATE SEQUENCE IF NOT EXISTS camp_dpid_seq_%s', NEW.id);
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    SQL

    execute <<~SQL
      CREATE OR REPLACE FUNCTION set_camp_display_id() RETURNS trigger AS $$
      BEGIN
        NEW.display_id := nextval('camp_dpid_seq_' || NEW.account_id);
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    SQL

    # --- Triggers ---------------------------------------------------------
    execute <<~SQL
      DROP TRIGGER IF EXISTS accounts_after_insert_row_tr ON accounts;
      CREATE TRIGGER accounts_after_insert_row_tr
        AFTER INSERT ON accounts
        FOR EACH ROW EXECUTE FUNCTION create_conv_dpid_seq();
    SQL

    execute <<~SQL
      DROP TRIGGER IF EXISTS conversations_before_insert_row_tr ON conversations;
      CREATE TRIGGER conversations_before_insert_row_tr
        BEFORE INSERT ON conversations
        FOR EACH ROW EXECUTE FUNCTION set_conv_display_id();
    SQL

    execute <<~SQL
      DROP TRIGGER IF EXISTS camp_dpid_before_insert ON accounts;
      CREATE TRIGGER camp_dpid_before_insert
        AFTER INSERT ON accounts
        FOR EACH ROW EXECUTE FUNCTION create_camp_dpid_seq();
    SQL

    execute <<~SQL
      DROP TRIGGER IF EXISTS campaigns_before_insert_row_tr ON campaigns;
      CREATE TRIGGER campaigns_before_insert_row_tr
        BEFORE INSERT ON campaigns
        FOR EACH ROW EXECUTE FUNCTION set_camp_display_id();
    SQL

    # --- Backfill per-account sequences for existing accounts ------------
    # Creates conv_dpid_seq_<id> and camp_dpid_seq_<id> for every account that
    # already exists, seeded just above the highest display_id currently used so
    # the next nextval() does not collide with rows already in the table.
    account_ids = connection.select_values('SELECT id FROM accounts')
    account_ids.each do |account_id|
      max_conv = connection.select_value(
        "SELECT COALESCE(MAX(display_id), 0) FROM conversations WHERE account_id = #{account_id}"
      ).to_i
      execute "CREATE SEQUENCE IF NOT EXISTS conv_dpid_seq_#{account_id} START WITH #{max_conv + 1}"

      max_camp = connection.select_value(
        "SELECT COALESCE(MAX(display_id), 0) FROM campaigns WHERE account_id = #{account_id}"
      ).to_i
      execute "CREATE SEQUENCE IF NOT EXISTS camp_dpid_seq_#{account_id} START WITH #{max_camp + 1}"
    end
  end

  def down
    execute <<~SQL
      DROP TRIGGER IF EXISTS conversations_before_insert_row_tr ON conversations;
      DROP TRIGGER IF EXISTS accounts_after_insert_row_tr ON accounts;
      DROP TRIGGER IF EXISTS camp_dpid_before_insert ON accounts;
      DROP TRIGGER IF EXISTS campaigns_before_insert_row_tr ON campaigns;
      DROP FUNCTION IF EXISTS set_conv_display_id();
      DROP FUNCTION IF EXISTS create_conv_dpid_seq();
      DROP FUNCTION IF EXISTS create_camp_dpid_seq();
      DROP FUNCTION IF EXISTS set_camp_display_id();
    SQL
  end
end
