#!/usr/bin/env bash
# One-command deploy for the Omni-Chat-AI stack on a single host (Docker Compose).
#
#   ./deploy.sh
#
# On first run it generates a .env with strong random secrets (you never edit secrets by hand),
# brings the whole stack up, and prints the admin-panel URL. All API keys (Anthropic, KeyCRM,
# Chatwoot, Telegram, …) are entered afterwards in the admin panel — not in any file.
set -euo pipefail
cd "$(dirname "$0")"

rand() { openssl rand -hex "${1:-32}"; }

if [[ ! -f .env ]]; then
  echo "▶ Generating .env with fresh secrets…"
  pg_pass="$(rand 16)"
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Secrets — keep private.

# --- Bootstrap / infra secrets (auto-generated; do not edit by hand) ---
APP_SECRET_KEY=$(rand 32)
OMNI_DATABASE_URL=postgresql+asyncpg://chatwoot:${pg_pass}@postgres:5432/omni_ai
PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:8080}

# --- Postgres / Redis ---
POSTGRES_USER=chatwoot
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=chatwoot_production
POSTGRES_HOST=postgres
REDIS_PASSWORD=$(rand 16)
REDIS_URL=redis://:PLACEHOLDER@redis:6379

# --- Chatwoot ---
SECRET_KEY_BASE=$(rand 64)
FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
RAILS_ENV=production
INSTALLATION_ENV=docker

# --- AI agent service ↔ Chatwoot (set in the admin panel after first boot) ---
CHATWOOT_BASE_URL=http://chatwoot:3000
CHATWOOT_API_ACCESS_TOKEN=
CHATWOOT_ACCOUNT_ID=1
CHATWOOT_HMAC_SECRET=

# --- Model gateway (provider key entered in the admin panel) ---
LITELLM_MASTER_KEY=sk-$(rand 16)
LITELLM_SALT_KEY=$(rand 32)
AGENT_MODEL=claude-primary

# --- KeyCRM (entered in the admin panel) ---
KEYCRM_API_KEY=
KEYCRM_BASE_URL=https://openapi.keycrm.app/v1

# --- Langfuse (infra secrets; public/secret keys entered in the admin panel) ---
LANGFUSE_NEXTAUTH_SECRET=$(rand 32)
LANGFUSE_SALT=$(rand 32)
LANGFUSE_ENCRYPTION_KEY=$(rand 32)
CLICKHOUSE_PASSWORD=$(rand 16)

# --- Connectors ---
EVOLUTION_API_KEY=evo-$(rand 12)
ECHAT_API_KEY=
ECHAT_WEBHOOK_SECRET=
EOF
  # Splice the generated redis password into REDIS_URL (kept readable above).
  redis_pass="$(grep '^REDIS_PASSWORD=' .env | cut -d= -f2)"
  sed -i.bak "s#redis://:PLACEHOLDER@redis:6379#redis://:${redis_pass}@redis:6379#" .env && rm -f .env.bak
  echo "✓ .env created."
else
  echo "▶ Reusing existing .env."
fi

echo "▶ Building and starting the stack…"
docker compose up -d --build

echo "▶ Waiting for Chatwoot to become healthy (first boot runs DB migrations, ~1–2 min)…"
for _ in $(seq 1 60); do
  if curl -fsS http://localhost:3000 >/dev/null 2>&1; then break; fi
  sleep 5
done

cat <<EOF

────────────────────────────────────────────────────────────────────
✅ Stack is up.

Next steps (all in the browser — no more file editing):
  1. Open the ADMIN PANEL:   http://localhost:8080/admin
     → create your administrator account, then add your API keys
       (Anthropic, KeyCRM, Telegram, …) under Settings.
  2. Chatwoot (agent inbox):  http://localhost:3000
  3. Langfuse (traces/eval):  http://localhost:3001

For a public HTTPS deploy, point a domain at this host and use the
included Caddyfile (see README → "Deploy on a VPS").
────────────────────────────────────────────────────────────────────
EOF
