#!/usr/bin/env bash
# One-command deploy for the Omni-Chat-AI stack on a single host (Docker Compose).
#
#   ./deploy.sh                         # local: services on localhost ports
#   DOMAIN=example.com ./deploy.sh      # public: automatic HTTPS via Caddy
#       (also set ACME_EMAIL=you@example.com for Let's Encrypt expiry notices)
#
# First run generates a .env with strong random secrets (you never edit secrets by hand),
# brings the whole stack up, bootstraps Chatwoot, and prints the URLs. All API keys (Anthropic,
# KeyCRM, Telegram, …) are entered afterwards in the admin panel — not in any file.
#
# DNS for a public deploy: point  example.com  AND  panel.example.com  (or *.example.com)
# at this server's IP before running.
set -euo pipefail
cd "$(dirname "$0")"

DOMAIN="${DOMAIN:-}"
ACME_EMAIL="${ACME_EMAIL:-}"
rand() { openssl rand -hex "${1:-32}"; }

if [[ -n "$DOMAIN" ]]; then
  PANEL_HOST="panel.${DOMAIN}"
  PUBLIC_BASE_URL="https://${PANEL_HOST}"
  FRONTEND_URL="https://${DOMAIN}"
  COMPOSE_PROFILES=(--profile tls)
else
  PUBLIC_BASE_URL="http://localhost:8080"
  FRONTEND_URL="http://localhost:3000"
  COMPOSE_PROFILES=()
fi

if [[ ! -f .env ]]; then
  echo "▶ Generating .env with fresh secrets…"
  pg_pass="$(rand 16)"
  redis_pass="$(rand 16)"
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Secrets — keep private.

# --- Bootstrap / infra secrets (auto-generated; do not edit by hand) ---
APP_SECRET_KEY=$(rand 32)
OMNI_DATABASE_URL=postgresql+asyncpg://chatwoot:${pg_pass}@postgres:5432/omni_ai
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# --- Postgres / Redis ---
POSTGRES_USER=chatwoot
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=chatwoot_production
POSTGRES_HOST=postgres
REDIS_PASSWORD=${redis_pass}
REDIS_URL=redis://:${redis_pass}@redis:6379

# --- Chatwoot ---
SECRET_KEY_BASE=$(rand 64)
FRONTEND_URL=${FRONTEND_URL}
RAILS_ENV=production
INSTALLATION_ENV=docker

# --- AI agent service ↔ Chatwoot (set in the admin panel after first boot) ---
CHATWOOT_BASE_URL=http://chatwoot:3000
CHATWOOT_API_ACCESS_TOKEN=
CHATWOOT_ACCOUNT_ID=1
CHATWOOT_HMAC_SECRET=

# --- Model gateway (provider key entered in the admin panel) ---
LITELLM_MASTER_KEY=sk-$(rand 16)
LITELLM_SALT_KEY=$(rand 32)
AGENT_MODEL=claude-primary

# --- KeyCRM (entered in the admin panel) ---
KEYCRM_API_KEY=
KEYCRM_BASE_URL=https://openapi.keycrm.app/v1

# --- Langfuse (infra secrets; public/secret keys entered in the admin panel) ---
LANGFUSE_NEXTAUTH_SECRET=$(rand 32)
LANGFUSE_SALT=$(rand 32)
LANGFUSE_ENCRYPTION_KEY=$(rand 32)
CLICKHOUSE_PASSWORD=$(rand 16)

# --- Connectors ---
EVOLUTION_API_KEY=evo-$(rand 12)
ECHAT_API_KEY=
ECHAT_WEBHOOK_SECRET=
EOF
  echo "✓ .env created."
else
  echo "▶ Reusing existing .env."
fi

# Generate the Caddy site config for a public (TLS) deploy.
if [[ -n "$DOMAIN" ]]; then
  echo "▶ Writing caddy/Caddyfile for ${DOMAIN} (panel: ${PANEL_HOST})…"
  mkdir -p caddy
  {
    if [[ -n "$ACME_EMAIL" ]]; then printf '{\n\temail %s\n}\n\n' "$ACME_EMAIL"; fi
    printf '%s {\n\treverse_proxy chatwoot:3000\n}\n\n' "$DOMAIN"
    printf '%s {\n\treverse_proxy ai-service:8080\n}\n' "$PANEL_HOST"
  } > caddy/Caddyfile
fi

echo "▶ Building and starting the stack…"
docker compose "${COMPOSE_PROFILES[@]}" up -d --build

echo "▶ Waiting for Chatwoot to become healthy (first boot runs DB migrations, ~1–2 min)…"
for _ in $(seq 1 60); do
  if curl -fsS http://localhost:3000 >/dev/null 2>&1; then break; fi
  sleep 5
done

# Bootstrap a Chatwoot admin + API token so the AI service can auto-provision channels.
if ! grep -q '^CHATWOOT_API_ACCESS_TOKEN=.\+' .env; then
  echo "▶ Bootstrapping Chatwoot admin + API token…"
  out="$(docker compose exec -T chatwoot bundle exec rails runner "$(cat scripts/bootstrap_chatwoot.rb)" 2>/dev/null | grep OMNI_BOOTSTRAP || true)"
  acct="$(sed -n 's/.*account_id=\([0-9]*\).*/\1/p' <<<"$out")"
  token="$(sed -n 's/.*token=\([A-Za-z0-9]*\).*/\1/p' <<<"$out")"
  if [[ -n "$token" ]]; then
    sed -i.bak "s#^CHATWOOT_API_ACCESS_TOKEN=.*#CHATWOOT_API_ACCESS_TOKEN=${token}#" .env
    sed -i.bak "s#^CHATWOOT_ACCOUNT_ID=.*#CHATWOOT_ACCOUNT_ID=${acct:-1}#" .env
    rm -f .env.bak
    echo "✓ Chatwoot API token wired into .env."
    docker compose "${COMPOSE_PROFILES[@]}" up -d ai-service
  else
    echo "⚠ Could not auto-bootstrap Chatwoot — set the admin token in the panel (Settings → Chatwoot)."
  fi
fi

if [[ -n "$DOMAIN" ]]; then
  panel_url="https://${PANEL_HOST}/admin"; chat_url="https://${DOMAIN}"
else
  panel_url="http://localhost:8080/admin"; chat_url="http://localhost:3000"
fi

cat <<EOF

────────────────────────────────────────────────────────────────────
✅ Stack is up.

Next steps (all in the browser — no more file editing):
  1. Open the ADMIN PANEL:   ${panel_url}
     → create your administrator account, then add your API keys
       (Anthropic, KeyCRM, Telegram, …) under Settings.
  2. Chatwoot (agent inbox):  ${chat_url}
$( [[ -n "$DOMAIN" ]] && echo "  3. HTTPS certificates are issued automatically by Caddy." )
────────────────────────────────────────────────────────────────────
EOF
