json.id resource.id
json.provider resource.provider
json.uid resource.uid
json.name resource.name
json.nickname resource.nickname
json.email resource.email
json.account_id resource.current_account_user.account_id
json.pubsub_token resource.pubsub_token
json.role resource.current_account_user.role
json.inviter_id resource.current_account_user.inviter_id
json.confirmed resource.confirmed?
json.avatar_url resource.avatar_url
