# Path: http/platform/users.http
# @name create_ticket
@account_id = 11005

POST {{api}}/platform/api/v1/tickets
Content-Type: application/json
api_access_token: {{api_access_token}}

{
  "title": "Test ticket",
  "description": "Test description",
  "account_id": 1,
  "status": "pending",
  "assigned_to": null,
  "user_id": 1,
  "conversation": {
    "id": 1
  },
  "labels": [
    {
      "id": 2
    }
  ]
}

###

# Path: http/platform/tickets.http
# @name update_ticket
PATCH {{api}}/platform/api/v1/tickets/23
Content-Type: application/json
api_access_token: {{api_access_token}}

{
  "title": "Test ticket",
  "description": "Test description",
  "assigned_to": {
    "id": 1
  },
  "resolved_at": "2024-07-31T00:53:06.000Z"
}

###

# Path: http/platform/users.http
# @name get_tickets
GET {{api}}/platform/api/v1/tickets
api_access_token: {{api_access_token}}

###

# Path: http/platform/users.http
# @name get_ticket
GET {{api}}/platform/api/v1/tickets/3
api_access_token: {{api_access_token}}