export const ONGOING_CAMPAIGN_EMPTY_STATE_CONTENT = [
  {
    id: 1,
    title: 'Онлайн-консультант по заказам',
    inbox: {
      id: 2,
      name: 'Сайт интернет-магазина',
      channel_type: 'Channel::WebWidget',
      phone_number: '',
    },
    sender: {
      id: 1,
      name: 'Айгерим',
    },
    message:
      'Здравствуйте! Нужна помощь с оформлением заказа и доставкой по Казахстану?',
    campaign_status: 'active',
    enabled: true,
    campaign_type: 'ongoing',
    trigger_rules: {
      url: 'https://shop.example.kz/catalog',
      time_on_page: 10,
    },
    trigger_only_during_business_hours: true,
    created_at: '2024-10-24T13:10:26.636Z',
    updated_at: '2024-10-24T13:10:26.636Z',
  },
  {
    id: 2,
    title: 'Подсказка по ценам в тенге',
    inbox: {
      id: 2,
      name: 'Сайт интернет-магазина',
      channel_type: 'Channel::WebWidget',
      phone_number: '',
    },
    sender: {
      id: 1,
      name: 'Дамир',
    },
    message: 'Подсказать по ценам и акциям? Все суммы отображаются в тенге.',
    campaign_status: 'active',
    enabled: false,
    campaign_type: 'ongoing',
    trigger_rules: {
      url: 'https://shop.example.kz/pricing',
      time_on_page: 10,
    },
    trigger_only_during_business_hours: false,
    created_at: '2024-10-24T13:11:08.763Z',
    updated_at: '2024-10-24T13:11:08.763Z',
  },
  {
    id: 3,
    title: 'Помощь с подключением услуги',
    inbox: {
      id: 2,
      name: 'Сайт интернет-магазина',
      channel_type: 'Channel::WebWidget',
      phone_number: '',
    },
    sender: {
      id: 1,
      name: 'Бот поддержки',
    },
    message:
      'Поможем подключить услугу за 2 минуты. Если нужно, передам оператору.',
    campaign_status: 'active',
    enabled: false,
    campaign_type: 'ongoing',
    trigger_rules: {
      url: 'https://shop.example.kz/setup',
      time_on_page: 10,
    },
    trigger_only_during_business_hours: false,
    created_at: '2024-10-24T13:11:44.285Z',
    updated_at: '2024-10-24T13:11:44.285Z',
  },
  {
    id: 4,
    title: 'Быстрая помощь по доставке',
    inbox: {
      id: 2,
      name: 'Сайт интернет-магазина',
      channel_type: 'Channel::WebWidget',
      phone_number: '',
    },
    sender: {
      id: 1,
      name: 'Нуржан',
    },
    message: 'Подскажем сроки доставки по Алматы, Астане и другим городам РК.',
    campaign_status: 'active',
    enabled: true,
    campaign_type: 'ongoing',
    trigger_rules: {
      url: 'https://siv.com',
      time_on_page: 200,
    },
    trigger_only_during_business_hours: false,
    created_at: '2024-10-29T19:54:33.741Z',
    updated_at: '2024-10-29T19:56:26.296Z',
  },
];

export const ONE_OFF_CAMPAIGN_EMPTY_STATE_CONTENT = [
  {
    id: 1,
    title: 'Запрос отзыва после доставки',
    inbox: {
      id: 6,
      name: 'Мобильная рассылка KZ',
      channel_type: 'Channel::Sms',
      phone_number: '+77071234567',
      provider: 'default',
    },
    message:
      'Спасибо за покупку! Оцените сервис и получите промокод на следующую покупку.',
    campaign_status: 'active',
    enabled: true,
    campaign_type: 'one_off',
    scheduled_at: 1729775588,
    audience: [
      { id: 4, type: 'Label' },
      { id: 5, type: 'Label' },
      { id: 6, type: 'Label' },
    ],
    trigger_rules: {},
    trigger_only_during_business_hours: false,
    created_at: '2024-10-24T13:13:08.496Z',
    updated_at: '2024-10-24T13:15:38.698Z',
  },
  {
    id: 2,
    title: 'Приветствие нового клиента',
    inbox: {
      id: 6,
      name: 'Мобильная рассылка KZ',
      channel_type: 'Channel::Sms',
      phone_number: '+77071234567',
      provider: 'default',
    },
    message:
      'Добро пожаловать! Если нужен подбор товара или консультация, мы на связи.',
    campaign_status: 'completed',
    enabled: true,
    campaign_type: 'one_off',
    scheduled_at: 1729732500,
    audience: [
      { id: 1, type: 'Label' },
      { id: 6, type: 'Label' },
      { id: 5, type: 'Label' },
      { id: 2, type: 'Label' },
      { id: 4, type: 'Label' },
    ],
    trigger_rules: {},
    trigger_only_during_business_hours: false,
    created_at: '2024-10-24T13:14:00.168Z',
    updated_at: '2024-10-24T13:15:38.707Z',
  },
  {
    id: 3,
    title: 'Предложение для нового B2B-клиента',
    inbox: {
      id: 6,
      name: 'Мобильная рассылка KZ',
      channel_type: 'Channel::Sms',
      phone_number: '+77071234567',
      provider: 'default',
    },
    message:
      'Рады сотрудничеству! Отправим прайс в тенге и условия оптовой доставки по РК.',
    campaign_status: 'active',
    enabled: true,
    campaign_type: 'one_off',
    scheduled_at: 1730368440,
    audience: [
      { id: 1, type: 'Label' },
      { id: 3, type: 'Label' },
      { id: 6, type: 'Label' },
      { id: 4, type: 'Label' },
      { id: 2, type: 'Label' },
      { id: 5, type: 'Label' },
    ],
    trigger_rules: {},
    trigger_only_during_business_hours: false,
    created_at: '2024-10-30T07:54:49.915Z',
    updated_at: '2024-10-30T07:54:49.915Z',
  },
  {
    id: 4,
    title: 'Стартовое сообщение для подписчиков',
    inbox: {
      id: 6,
      name: 'Мобильная рассылка KZ',
      channel_type: 'Channel::Sms',
      phone_number: '+77071234567',
      provider: 'default',
    },
    message:
      'Спасибо за подписку! Напишите нам, если нужно уточнить наличие или сроки доставки.',
    campaign_status: 'completed',
    enabled: true,
    campaign_type: 'one_off',
    scheduled_at: 1730304840,
    audience: [
      { id: 1, type: 'Label' },
      { id: 3, type: 'Label' },
      { id: 6, type: 'Label' },
    ],
    trigger_rules: {},
    trigger_only_during_business_hours: false,
    created_at: '2024-10-29T16:14:10.374Z',
    updated_at: '2024-10-30T16:15:03.157Z',
  },
];
