export default [
  {
    id: 1,
    name: 'Premium SLA',
    description:
      'SLA for chatwoot cloud premium and self-hosted premium customers.  SLA for chatwoot cloud premium and self-hosted premium customers',
    first_response_time_threshold: 14400,
    next_response_time_threshold: 18000,
    resolution_time_threshold: 86400,
    only_during_business_hours: true,
  },
  {
    id: 2,
    name: 'Enterprise SLA',
    description:
      'SLA for chatwoot enterprise and self-hosted enterprise customers.',
    first_response_time_threshold: 600,
    next_response_time_threshold: 2400,
    resolution_time_threshold: 3600,
    only_during_business_hours: false,
  },
  {
    id: 3,
    name: 'Business SLA',
    description:
      'Chatwoot cloud Business and self-hosted Business customers SLA',
    first_response_time_threshold: null,
    next_response_time_threshold: null,
    resolution_time_threshold: null,
    only_during_business_hours: false,
  },
  {
    id: 4,
    name: 'Hacker SLA',
    description: '',
    first_response_time_threshold: 60,
    next_response_time_threshold: 120,
    resolution_time_threshold: 180,
    only_during_business_hours: false,
  },
  {
    id: 5,
    name: 'SLA',
    description: '',
    first_response_time_threshold: 120,
    next_response_time_threshold: 300,
    resolution_time_threshold: 21600,
    only_during_business_hours: false,
  },
  {
    id: 6,
    name: 'ALla',
    description: '',
    first_response_time_threshold: 5400,
    next_response_time_threshold: 9000,
    resolution_time_threshold: 23040,
    only_during_business_hours: false,
  },
  {
    id: 7,
    name: '10',
    description: '',
    first_response_time_threshold: 120,
    next_response_time_threshold: null,
    resolution_time_threshold: null,
    only_during_business_hours: false,
  },
  {
    id: 8,
    name: '11',
    description: '',
    first_response_time_threshold: null,
    next_response_time_threshold: 240,
    resolution_time_threshold: null,
    only_during_business_hours: false,
  },
  {
    id: 9,
    name: '12',
    description: '',
    first_response_time_threshold: null,
    next_response_time_threshold: null,
    resolution_time_threshold: 300,
    only_during_business_hours: false,
  },
  {
    id: 10,
    name: '14',
    description: '',
    first_response_time_threshold: null,
    next_response_time_threshold: null,
    resolution_time_threshold: null,
    only_during_business_hours: false,
  },
];
