#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# Source nvm to make npm/npx available in git hooks
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# lint js and vue files
npx --no-install lint-staged

# lint only staged ruby files
git diff --name-only --cached | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs bundle exec rubocop --force-exclusion

# stage rubocop changes to files
# git diff --name-only --cached | xargs git add
