name: Chatwoot restarter Job

on:
  workflow_dispatch:

jobs:
  run-cron-job:
    runs-on: self-hosted

    steps:
      - name: Deploy production Chatwoot
        run: |
          cd /home/ec2-user/chatwoot
          docker-compose pull
          docker-compose build
          docker-compose down
          docker-compose up -d --remove-orphans