name: Deploy to Railway

on:
  push:
    branches:
      - overlay/main  # Tu rama principal de trabajo
      - main          # Por si cambias a main
    tags:
      - v*            # Para releases
  workflow_dispatch:  # Para ejecutar manualmente

env:
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          bundle install
          npm install

      - name: Run Ruby tests
        run: |
          bundle exec rspec spec/ --fail-fast

      - name: Run JavaScript tests
        run: |
          npm test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          bundle install
          npm install

      - name: Precompile assets
        run: |
          RAILS_ENV=production bundle exec rails assets:precompile

      - name: Create deployment package
        run: |
          tar -czf chatwoot-deploy.tar.gz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='tmp' \
            --exclude='log' \
            --exclude='coverage' \
            --exclude='spec' \
            .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatwoot-build
          path: chatwoot-deploy.tar.gz
          retention-days: 1

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/overlay/main' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: chatwoot-build
          path: .

      - name: Extract build
        run: |
          tar -xzf chatwoot-deploy.tar.gz

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_NAME || 'chatwoot' }}

      - name: Notify deployment
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
