name: Deploy Production (Railway)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node for Railway CLI
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Generate SDK types
        run: |
          npm install -g pnpm@10.2.0
          pnpm install
          pnpm sdk:wsc

      - name: Deploy to Railway (production)
        uses: railwayapp/railway-action@v2
        with:
          serviceId: ${{ secrets.RAILWAY_SERVICE_ID_PROD }}
          environmentId: ${{ secrets.RAILWAY_ENV_ID_PROD }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run DB migrations (production)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID_PROD }}
          ENV_ID: ${{ secrets.RAILWAY_ENV_ID_PROD }}
        run: |
          railway run --service $SERVICE_ID --environment $ENV_ID -- bundle exec rails db:migrate
