name: Deploy to Staging

on:
  push:
    branches:
      - development
  pull_request:
    types: [closed]
    branches:
      - development

jobs:
  build:
    name: "Fetching changes"
    runs-on: ubuntu-latest

    steps:
      - name: Execute commands via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 15.206.194.241
          username: "chatwoot"
          key: ${{ secrets.ONECHAT_STAGING_PRIVATE_KEY }}
          script: |
            echo "Deploying to EC2"
            cd /home/chatwoot/onehash-chat
            git pull origin development
            bundle install
            yarn install
            rake assets:precompile RAILS_ENV=production
            RAILS_ENV=production bundle exec rake db:migrate
            sudo systemctl restart chatwoot.target
            exit
            EOF