export default [
  {
    meta: {
      sender: {
        id: 1,
        name: 'sender1',
        thumbnail: '',
        channel: 'Channel::WebWidget',
      },
      assignee: null,
    },
    id: 1,
    messages: [
      {
        id: 1,
        content: 'Hello',
        account_id: 1,
        inbox_id: 1,
        conversation_id: 1,
        message_type: 1,
        created_at: 1578555084,
        updated_at: '2020-01-09T07:31:24.419Z',
        private: false,
        user_id: 1,
        status: 'sent',
        source_id: null,
        content_type: 'text',
        content_attributes: {},
        sender: {
          name: 'Sender 1',
          avatar_url: 'random_url',
        },
      },
    ],
    inbox_id: 1,
    status: 0,
    timestamp: 1578555084,
    contact_last_seen_at: 0,
    agent_last_seen_at: 1578555084,
    unread_count: 0,
  },
  {
    meta: {
      sender: {
        id: 2,
        name: 'sender1',
        thumbnail: '',
        channel: 'Channel::WebWidget',
      },
      assignee: null,
    },
    id: 2,
    messages: [
      {
        id: 2,
        content: 'Hello',
        account_id: 1,
        inbox_id: 2,
        conversation_id: 2,
        message_type: 1,
        created_at: 1578555084,
        updated_at: '2020-01-09T07:31:24.419Z',
        private: false,
        user_id: 2,
        status: 'sent',
        source_id: null,
        content_type: 'text',
        content_attributes: {},
        sender: {
          name: 'Sender 1',
          avatar_url: 'random_url',
        },
      },
    ],
    inbox_id: 2,
    status: 0,
    timestamp: 1578555084,
    contact_last_seen_at: 0,
    agent_last_seen_at: 1578555084,
    unread_count: 0,
  },
];
